(in-package #:clinedi/tests)

;;;; -- Incremental Editor Tests --

(defun editor-tests--assert (condition control &rest arguments)
  "Signal a test failure described by CONTROL unless CONDITION is true."
  (unless condition
    (error (apply #'format nil control arguments)))
  nil)

(defun editor-tests--event (editor event expected-action)
  "Apply EVENT and require EXPECTED-ACTION, returning its payload."
  (multiple-value-bind (action payload)
      (line-editor-handle-event editor event)
    (editor-tests--assert (eq action expected-action)
                          "Event ~S returned ~S instead of ~S."
                          event action expected-action)
    payload))

(defun editor-tests--symbol-command (editor event)
  "Record EVENT in EDITOR and return a test-specific action and payload."
  (line-editor-set-text editor "symbol-command")
  (values :custom event))

(defun editor-tests--test-keymaps ()
  "Test inheritance, compound lookup, copying, dispatch, and isolation."
  (let* ((parent
           (make-keymap :bindings '((:left . :right)
                                    (:insert . :paste))))
         (child
           (make-keymap :parent parent
                        :bindings '(((:insert "exact") . :kill-line)
                                    (:home . :end)))))
    (multiple-value-bind (command present-p)
        (keymap-lookup child '(:insert "exact"))
      (editor-tests--assert (and present-p (eq command :kill-line))
                            "An exact compound binding must win."))
    (multiple-value-bind (command present-p)
        (keymap-lookup child '(:insert "other"))
      (editor-tests--assert (and present-p (eq command :paste))
                            "A compound event must fall back to its head."))
    (multiple-value-bind (command present-p)
        (keymap-lookup child :left)
      (editor-tests--assert (and present-p (eq command :right))
                            "A child keymap must fall back to its parent."))
    (keymap-bind child :left nil)
    (multiple-value-bind (command present-p)
        (keymap-lookup child :left)
      (editor-tests--assert (and present-p (null command))
                            "A NIL local command must mask its parent."))
    (keymap-unbind child :left)
    (editor-tests--assert (eq (keymap-lookup child :left) :right)
                          "Unbinding must reveal a parent binding.")
    (let ((snapshot (keymap-bindings child)))
      (setf (rest (assoc :home snapshot)) :left)
      (editor-tests--assert (eq (keymap-lookup child :home) :end)
                            "Binding snapshots must be detached."))
    (let ((copy (copy-keymap child)))
      (keymap-bind child :home :left)
      (keymap-bind parent :left :home)
      (editor-tests--assert (eq (keymap-lookup copy :home) :end)
                            "A copied local binding must be detached.")
      (editor-tests--assert (eq (keymap-lookup copy :left) :right)
                            "A copied parent binding must be detached.")
      (editor-tests--assert (not (eq (keymap-parent copy) parent))
                            "COPY-KEYMAP must copy its parent chain.")))
  (let ((first-map (default-line-editor-keymap))
        (second-map (default-line-editor-keymap)))
    (keymap-bind first-map :left :right)
    (editor-tests--assert (eq (keymap-lookup second-map :left) :left)
                          "Default keymaps must be independent."))
  (let ((first-editor (make-line-editor))
        (second-editor (make-line-editor)))
    (keymap-bind (line-editor-keymap first-editor) :left :right)
    (editor-tests--assert
     (eq (line-editor-command-for-event second-editor :left) :left)
     "Default editor construction must not share a mutable keymap."))
  (let* ((keymap (default-line-editor-keymap))
         (editor (line-editor-create :text "abc" :keymap keymap)))
    (editor-tests--assert (eq (line-editor-keymap editor) keymap)
                          "The named constructor must retain its keymap.")
    (keymap-bind keymap '(:insert "x") :kill-line)
    (editor-tests--event editor '(:insert "x") :continue)
    (editor-tests--assert (string= (line-editor-text editor) "")
                          "An exact event binding must control dispatch.")
    (editor-tests--event editor '(:insert "y") :continue)
    (editor-tests--assert (string= (line-editor-text editor) "y")
                          "A head binding must handle other compound events.")
    (keymap-bind keymap :home #'editor-tests--symbol-command)
    (multiple-value-bind (action payload)
        (line-editor-handle-event editor :home)
      (editor-tests--assert
       (and (eq action :custom)
            (eq payload :home)
            (string= (line-editor-text editor) "symbol-command"))
       "A function command must receive the editor and original event."))
    (keymap-bind keymap :end 'editor-tests--symbol-command)
    (multiple-value-bind (action payload)
        (line-editor-handle-event editor :end)
      (editor-tests--assert
       (and (eq action :custom) (eq payload :end))
       "A non-keyword fbound symbol must be a command designator."))
    (multiple-value-bind (action payload)
        (line-editor-execute-command editor :clear-screen :synthetic)
      (editor-tests--assert
       (and (eq action :clear-screen) (null payload))
       "Public command execution must expose built-in commands.")))
  nil)

(defun editor-tests--test-editing ()
  "Test insertion, grapheme movement, deletion, and kill operations."
  (let* ((accent (string (code-char #x301)))
         (text   (concatenate 'string "e" accent "x"))
         (editor (make-line-editor :text text :cursor 1)))
    (editor-tests--assert (= (line-editor-cursor editor) 2)
                          "The constructor must advance an interior cursor.")
    (editor-tests--event editor :left :continue)
    (editor-tests--assert (zerop (line-editor-cursor editor))
                          "Left must cross a complete grapheme.")
    (editor-tests--event editor :right :continue)
    (editor-tests--assert (= (line-editor-cursor editor) 2)
                          "Right must cross a complete grapheme.")
    (editor-tests--event editor :backspace :continue)
    (editor-tests--assert (string= (line-editor-text editor) "x")
                          "Backspace must delete a complete grapheme."))
  (let ((editor (make-line-editor :text "alpha  beta gamma" :cursor 0)))
    (editor-tests--event editor :word-right :continue)
    (editor-tests--assert (= (line-editor-cursor editor) 5)
                          "Word-right must reach the end of the next word.")
    (editor-tests--event editor :word-right :continue)
    (editor-tests--assert (= (line-editor-cursor editor) 11)
                          "Word-right must cross separating whitespace.")
    (editor-tests--event editor :word-left :continue)
    (editor-tests--assert (= (line-editor-cursor editor) 7)
                          "Word-left must reach the current word's start.")
    (editor-tests--event editor :word-left :continue)
    (editor-tests--assert (zerop (line-editor-cursor editor))
                          "Word-left must cross separating whitespace."))
  (let ((editor (make-line-editor :text "alpha beta  ")))
    (editor-tests--event editor :kill-word :continue)
    (editor-tests--assert (string= (line-editor-text editor) "alpha ")
                          "Kill-word must remove trailing space and one word.")
    (editor-tests--event editor :home :continue)
    (editor-tests--event editor '(:insert "X") :continue)
    (editor-tests--event editor :right :continue)
    (editor-tests--event editor :kill-to-end :continue)
    (editor-tests--assert (string= (line-editor-text editor) "Xa")
                          "Kill-to-end must preserve text through the cursor.")
    (editor-tests--event editor :kill-line :continue)
    (editor-tests--assert (and (string= (line-editor-text editor) "")
                               (zerop (line-editor-cursor editor)))
                          "Kill-line must clear text and cursor."))
  nil)

(defun editor-tests--test-history ()
  "Test copied, bounded history and restoration of a traversed draft."
  (let* ((source  (vector "one" "two"))
         (editor  (make-line-editor :text "draft"
                                    :history source
                                    :history-limit 2)))
    (setf (aref source 1) "changed")
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "two")
                          "History must be detached from its input sequence.")
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "one")
                          "Repeated history-previous must move toward older entries.")
    (editor-tests--event editor :history-next :continue)
    (editor-tests--assert (string= (line-editor-text editor) "two")
                          "History-next must move toward newer entries.")
    (editor-tests--event editor :history-next :continue)
    (editor-tests--assert (string= (line-editor-text editor) "draft")
                          "Leaving history must restore the original draft.")
    (line-editor-add-history editor "three")
    (line-editor-add-history editor "three")
    (editor-tests--assert (equalp (line-editor-history editor)
                                  #("two" "three"))
                          "History must enforce its limit and suppress duplicates."))
  nil)

(defun editor-tests--test-filtered-history ()
  "Test fixed-query filtered traversal and exact draft restoration."
  (flet ((contains-p (query entry)
           (search query entry)))
    (let ((editor
            (make-line-editor
             :text "needle"
             :cursor 2
             :history #("old needle"
                        "duplicate needle"
                        "unrelated"
                        "duplicate needle"
                        "new needle"
                        "only ne")
             :history-match-function #'contains-p)))
      (dolist (expected '("new needle" "duplicate needle"
                          "duplicate needle" "old needle" "old needle"))
        (editor-tests--event editor :history-previous :continue)
        (editor-tests--assert (string= (line-editor-text editor) expected)
                              "Filtered history expected ~S, got ~S."
                              expected (line-editor-text editor)))
      (editor-tests--assert
       (= (line-editor-cursor editor) (length "old needle"))
       "Recalled history must place the cursor at the entry's end.")
      (dolist (expected '("duplicate needle" "duplicate needle"
                          "new needle" "needle"))
        (editor-tests--event editor :history-next :continue)
        (editor-tests--assert (string= (line-editor-text editor) expected)
                              "Forward filtered history expected ~S, got ~S."
                              expected (line-editor-text editor)))
      (editor-tests--assert (= (line-editor-cursor editor) 2)
                            "Leaving history must restore the draft cursor.")
      (editor-tests--event editor :history-next :continue)
      (editor-tests--assert (and (string= (line-editor-text editor) "needle")
                                 (= (line-editor-cursor editor) 2))
                            "History-next outside traversal must be a no-op."))
    (let ((editor
            (make-line-editor
             :text "missing"
             :cursor 3
             :history #("alpha beta" "release")
             :history-match-function #'contains-p)))
      (editor-tests--event editor :history-previous :continue)
      (editor-tests--event editor :history-next :continue)
      (editor-tests--assert
       (and (string= (line-editor-text editor) "missing")
            (= (line-editor-cursor editor) 3))
       "A history search without matches must preserve the draft.")
      (line-editor-set-text editor "beta")
      (editor-tests--event editor :history-previous :continue)
      (editor-tests--assert (string= (line-editor-text editor) "alpha beta")
                            "A new draft must start a fresh history search.")
      (editor-tests--event editor '(:insert "!") :continue)
      (editor-tests--event editor :history-next :continue)
      (editor-tests--assert (string= (line-editor-text editor) "alpha beta!")
                            "Editing a recalled entry must end traversal.")))
  nil)

(defun editor-tests--test-vertical-movement ()
  "Test visual-row movement across explicit, short, wrapped, and wide rows."
  (let* ((text (format nil "abcd~%xy~%abcdef"))
         (editor (make-line-editor :text text)))
    (editor-tests--assert
     (line-editor-move-vertical editor -1 :columns 80 :prompt-width 2)
     "Up must reach the previous explicit line.")
    (editor-tests--assert (= (line-editor-cursor editor) 7)
                          "Up must stop at the end of a shorter line.")
    (line-editor-move-vertical editor -1 :columns 80 :prompt-width 2)
    (editor-tests--assert (= (line-editor-cursor editor) 4)
                          "Repeated Up must preserve the preferred column.")
    (line-editor-move-vertical editor 1 :columns 80 :prompt-width 2)
    (editor-tests--assert (= (line-editor-cursor editor) 7)
                          "Down must revisit the short line.")
    (line-editor-move-vertical editor 1 :columns 80 :prompt-width 2)
    (editor-tests--assert (= (line-editor-cursor editor) (length text))
                          "Down must restore the preferred column.")
    (line-editor-move-vertical editor -1 :columns 80 :prompt-width 2)
    (editor-tests--event editor :left :continue)
    (line-editor-move-vertical editor 1 :columns 80 :prompt-width 2)
    (editor-tests--assert (= (line-editor-cursor editor) 9)
                          "Horizontal movement must reset the preferred column."))
  (let ((editor (make-line-editor :text "abcdefghij")))
    (line-editor-move-vertical editor -1 :columns 5 :prompt-width 2)
    (editor-tests--assert (= (line-editor-cursor editor) 5)
                          "Up must navigate a terminal-wrapped row.")
    (line-editor-move-vertical editor -1 :columns 5 :prompt-width 2)
    (editor-tests--assert (zerop (line-editor-cursor editor))
                          "Up must account for the prompt on the first row.")
    (editor-tests--assert
     (not (line-editor-move-vertical editor -1
                                    :columns 5
                                    :prompt-width 2))
     "Movement must report the visual boundary for history fallback."))
  (let* ((text (format nil "猫a~%犬b"))
         (editor (make-line-editor :text text)))
    (line-editor-move-vertical editor -1 :columns 20 :prompt-width 0)
    (editor-tests--assert (= (line-editor-cursor editor) 2)
                          "Vertical movement must preserve Unicode cell columns."))
  nil)

(defun editor-tests--test-actions ()
  "Test submission, line events, external actions, and end-of-input behavior."
  (let ((editor (make-line-editor :text "abc" :cursor 1)))
    (editor-tests--event editor :insert-newline :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%bc"))
                          "Insert-newline must add a logical input line.")
    (editor-tests--event editor :end-of-input :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%c"))
                          "End-of-input must delete at an interior cursor.")
    (editor-tests--event editor :end :continue)
    (editor-tests--event editor :end-of-input :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%c"))
                          "End-of-input at non-empty end must preserve text.")
    (editor-tests--assert
     (string= (editor-tests--event editor :submit :submit)
              (format nil "a~%c"))
     "Submit must return the complete line.")
    (editor-tests--assert (string= (line-editor-text editor) "")
                          "Submit must clear the editor.")
    (editor-tests--event editor :end-of-input :end-of-input)
    (line-editor-set-text editor "partial")
    (editor-tests--event editor :stream-end :end-of-input)
    (editor-tests--assert (string= (line-editor-text editor) "partial")
                          "Physical stream end must preserve partial input.")
    (line-editor-clear editor)
    (editor-tests--assert
     (string= (editor-tests--event editor '(:line "stream line") :submit)
              "stream line")
     "A line event must replace and submit the buffer.")
    (dolist (case '((:complete :complete)
                    (:complete-previous :complete-previous)
                    (:up :up)
                    (:down :down)
                    (:escape :escape)
                    (:clear-screen :clear-screen)
                    (:interrupt :interrupt)
                    (:unknown :ignored)))
      (editor-tests--event editor (first case) (second case))))
  nil)

(defun editor-tests--test-render ()
  "Test plain rendering, cursor width, and an unaccepted suggestion suffix."
  (let ((editor (make-line-editor :text "abcd" :cursor 2)))
    (multiple-value-bind (display cursor-column)
        (line-editor-render editor :suggestion "ignored")
      (editor-tests--assert (string= display "abcd")
                            "Suggestions must be hidden before the text end.")
      (editor-tests--assert (= cursor-column 2)
                            "Render must return the cursor's cell offset."))
    (editor-tests--event editor :end :continue)
    (multiple-value-bind (display cursor-column)
        (line-editor-render editor :suggestion " suggestion")
      (editor-tests--assert (string= display "abcd suggestion")
                            "Render must append an end-of-line suggestion.")
      (editor-tests--assert (= cursor-column 4)
                            "A suggestion must not move the real cursor.")))
  nil)

(defun editor-tests--test-named-constructor ()
  "Test public construction paths and their history matcher defaults."
  (let ((editor
          (line-editor-create
           :text "ready"
           :history #("older")
           :history-match-function (lambda (query entry)
                                     (declare (ignore query entry))
                                     nil))))
    (editor-tests--assert (string= (line-editor-text editor) "ready")
                          "The named constructor must preserve initial text.")
    (editor-tests--assert
     (functionp (line-editor-history-match-function editor))
     "The named constructor must retain the history matcher.")
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "ready")
                          "The named constructor must apply its matcher."))
  (let ((editor
          (make-instance 'clinedi:line-editor
                         :text "draft"
                         :cursor 5
                         :history (make-array 1
                                              :adjustable t
                                              :fill-pointer 1
                                              :initial-element "older")
                         :history-limit 10)))
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "older")
                          "Direct construction must default to unfiltered history."))
  nil)

(defun run-editor-tests ()
  "Run the complete incremental editor test group."
  (editor-tests--test-keymaps)
  (editor-tests--test-editing)
  (editor-tests--test-vertical-movement)
  (editor-tests--test-history)
  (editor-tests--test-filtered-history)
  (editor-tests--test-actions)
  (editor-tests--test-named-constructor)
  (editor-tests--test-render)
  t)
