(in-package #:clinedi/tests)

;;;; -- Incremental Editor Tests --

(defun editor-tests--assert (condition control &rest arguments)
  "Signal a test failure described by CONTROL unless CONDITION is true."
  (unless condition
    (error (apply #'format nil control arguments)))
  nil)

(defun editor-tests--event (editor event expected-action)
  "Apply EVENT and require EXPECTED-ACTION, returning its payload."
  (multiple-value-bind (action payload)
      (line-editor-handle-event editor event)
    (editor-tests--assert (eq action expected-action)
                          "Event ~S returned ~S instead of ~S."
                          event action expected-action)
    payload))

(defun editor-tests--test-editing ()
  "Test insertion, grapheme movement, deletion, and kill operations."
  (let* ((accent (string (code-char #x301)))
         (text   (concatenate 'string "e" accent "x"))
         (editor (make-line-editor :text text :cursor 1)))
    (editor-tests--assert (= (line-editor-cursor editor) 2)
                          "The constructor must advance an interior cursor.")
    (editor-tests--event editor :left :continue)
    (editor-tests--assert (zerop (line-editor-cursor editor))
                          "Left must cross a complete grapheme.")
    (editor-tests--event editor :right :continue)
    (editor-tests--assert (= (line-editor-cursor editor) 2)
                          "Right must cross a complete grapheme.")
    (editor-tests--event editor :backspace :continue)
    (editor-tests--assert (string= (line-editor-text editor) "x")
                          "Backspace must delete a complete grapheme."))
  (let ((editor (make-line-editor :text "alpha beta  ")))
    (editor-tests--event editor :kill-word :continue)
    (editor-tests--assert (string= (line-editor-text editor) "alpha ")
                          "Kill-word must remove trailing space and one word.")
    (editor-tests--event editor :home :continue)
    (editor-tests--event editor '(:insert "X") :continue)
    (editor-tests--event editor :right :continue)
    (editor-tests--event editor :kill-to-end :continue)
    (editor-tests--assert (string= (line-editor-text editor) "Xa")
                          "Kill-to-end must preserve text through the cursor.")
    (editor-tests--event editor :kill-line :continue)
    (editor-tests--assert (and (string= (line-editor-text editor) "")
                               (zerop (line-editor-cursor editor)))
                          "Kill-line must clear text and cursor."))
  nil)

(defun editor-tests--test-history ()
  "Test copied, bounded history and restoration of a traversed draft."
  (let* ((source  (vector "one" "two"))
         (editor  (make-line-editor :text "draft"
                                    :history source
                                    :history-limit 2)))
    (setf (aref source 1) "changed")
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "two")
                          "History must be detached from its input sequence.")
    (editor-tests--event editor :history-previous :continue)
    (editor-tests--assert (string= (line-editor-text editor) "one")
                          "Repeated history-previous must move toward older entries.")
    (editor-tests--event editor :history-next :continue)
    (editor-tests--assert (string= (line-editor-text editor) "two")
                          "History-next must move toward newer entries.")
    (editor-tests--event editor :history-next :continue)
    (editor-tests--assert (string= (line-editor-text editor) "draft")
                          "Leaving history must restore the original draft.")
    (line-editor-add-history editor "three")
    (line-editor-add-history editor "three")
    (editor-tests--assert (equalp (line-editor-history editor)
                                  #("two" "three"))
                          "History must enforce its limit and suppress duplicates."))
  nil)

(defun editor-tests--test-actions ()
  "Test submission, line events, external actions, and end-of-input behavior."
  (let ((editor (make-line-editor :text "abc" :cursor 1)))
    (editor-tests--event editor :insert-newline :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%bc"))
                          "Insert-newline must add a logical input line.")
    (editor-tests--event editor :end-of-input :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%c"))
                          "End-of-input must delete at an interior cursor.")
    (editor-tests--event editor :end :continue)
    (editor-tests--event editor :end-of-input :continue)
    (editor-tests--assert (string= (line-editor-text editor)
                                    (format nil "a~%c"))
                          "End-of-input at non-empty end must preserve text.")
    (editor-tests--assert
     (string= (editor-tests--event editor :submit :submit)
              (format nil "a~%c"))
     "Submit must return the complete line.")
    (editor-tests--assert (string= (line-editor-text editor) "")
                          "Submit must clear the editor.")
    (editor-tests--event editor :end-of-input :end-of-input)
    (line-editor-set-text editor "partial")
    (editor-tests--event editor :stream-end :end-of-input)
    (editor-tests--assert (string= (line-editor-text editor) "partial")
                          "Physical stream end must preserve partial input.")
    (line-editor-clear editor)
    (editor-tests--assert
     (string= (editor-tests--event editor '(:line "stream line") :submit)
              "stream line")
     "A line event must replace and submit the buffer.")
    (dolist (case '((:complete :complete)
                    (:escape :escape)
                    (:clear-screen :clear-screen)
                    (:interrupt :interrupt)
                    (:unknown :ignored)))
      (editor-tests--event editor (first case) (second case))))
  nil)

(defun editor-tests--test-render ()
  "Test plain rendering, cursor width, and an unaccepted suggestion suffix."
  (let ((editor (make-line-editor :text "abcd" :cursor 2)))
    (multiple-value-bind (display cursor-column)
        (line-editor-render editor :suggestion "ignored")
      (editor-tests--assert (string= display "abcd")
                            "Suggestions must be hidden before the text end.")
      (editor-tests--assert (= cursor-column 2)
                            "Render must return the cursor's cell offset."))
    (editor-tests--event editor :end :continue)
    (multiple-value-bind (display cursor-column)
        (line-editor-render editor :suggestion " suggestion")
      (editor-tests--assert (string= display "abcd suggestion")
                            "Render must append an end-of-line suggestion.")
      (editor-tests--assert (= cursor-column 4)
                            "A suggestion must not move the real cursor.")))
  nil)

(defun editor-tests--test-named-constructor ()
  "Test the application-oriented named constructor."
  (let ((editor (line-editor-create :text "ready")))
    (editor-tests--assert (string= (line-editor-text editor) "ready")
                          "The named constructor must preserve initial text."))
  nil)

(defun run-editor-tests ()
  "Run the complete incremental editor test group."
  (editor-tests--test-editing)
  (editor-tests--test-history)
  (editor-tests--test-actions)
  (editor-tests--test-named-constructor)
  (editor-tests--test-render)
  t)
